#!/bin/bash

_other_installs () {
   if [[ $OTHER_INSTALLS != "None" ]]
   then
    apt install $OTHER_INSTALLS -y
   fi
}

_externals () {
   if [[ $OTHER_CMD != "None" ]]
   then
      $OTHER_CMD
   fi
}

apt update && apt upgrade -y
apt install git -y
_other_installs
pip3 install -U pip
git clone $REPO_URL Github_Repo
cd Github_Repo

# Check if Dockerfile exists
if [ -f "Dockerfile" ]; then
    # Build Docker image
    docker build -t justcm .
else
    echo "Error: Dockerfile not found in the repository."
    exit 1
fi

# Run Docker container
docker run justcm bash start.sh
